env:
  ITCH_USERNAME: carlos-michael
  ITCH_GAMEID: unwilting
  GODOT_VERSION: 4.3
  GODOT_BUILD : dev4-mono
  # TODO this is not working yet, web step is just commented out
  DEPLOY_WEB: false
  DEPLOY_MAC: true
  DEPLOY_WINDOWS: true
  DEPLOY_LINUX: true

# Whenever a tag push matching pattern "v*" then run the job
on: 
    release:
      types: [created]
    push:
        # only run on branch names /main and /playtest
        branches:
            # - main
            - playtest
            - workflows
#
jobs:
    #godot default export
    export_game:
      # Always use ubuntu-latest for this action
      runs-on: ubuntu-latest
      # Add permission for release creation. Can be made narrower according to your needs
      permissions: write-all
      # Job name, can be anything
      name: Export Game
      steps:
        # Always include the checkout step so that 
        # your project is available for Godot to export
        - name: checkout
          uses: actions/checkout@v3.3.0
      
        - name: export game
          id: export
          # Use latest version (see releases for all versions)
          uses: firebelley/godot-export@v5.2.1
          with:
            # Defining all the required inputs
            godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.3/dev4/mono/Godot_v4.3-dev4_mono_linux_x86_64.zip
            godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.3/dev4/mono/Godot_v4.3-dev4_mono_export_templates.tpz
            relative_project_path: ./
            archive_output: true
        - uses: actions/upload-artifact@v3
          with:
              name: godot-export
              path: ${{ steps.export.outputs.archive_directory }}
    # deploy to itch step web / windows / linux
    # deploy_web:
    #   needs: export_game
    #   runs-on: ubuntu-latest
    #   if: github.ref == 'refs/heads/main'
    #   steps:
    #     - uses: actions/download-artifact@v2
    #       with:
    #         name: godot-export
    #         path: ./
    #     - name: Deploy - Itch.io - web
    #       uses: KikimoraGames/itch-publish@v0.0.3
    #       with:
    #           butlerApiKey: ${{ secrets.BUTLER_CREDENTIALS }}
    #           gameData: ./Web.zip
    #           itchUsername: ${{ env.ITCH_USERNAME }}
    #           itchGameId: ${{ env.ITCH_GAMEID }}
    #           buildChannel: web
    #           buildNumber: ${{ github.run_number }}
    deploy_windows:
      needs: export_game
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v2
          with:
            name: godot-export
            path: ./
        - name: Deploy - Itch.io - windows
          uses: KikimoraGames/itch-publish@v0.0.3
          with:
              butlerApiKey: ${{ secrets.BUTLER_CREDENTIALS }}
              gameData: ./win.zip

              itchUsername: ${{ env.ITCH_USERNAME }}
              itchGameId: ${{ env.ITCH_GAMEID }}
              buildChannel: windows
              buildNumber: unwilting-${{ github.ref}}
    deploy_mac:
      needs: export_game
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v2
          with:
            name: godot-export
            path: ./
        - name: Unzip macOS.zip
          run: |
            unzip macOS.zip -d unzipped
            unzip unzipped/flower-water-godot-mac.zip -d finalUnzipped

             
        - name: Deploy - Itch.io - Mac
          uses: KikimoraGames/itch-publish@v0.0.3
          with:
              butlerApiKey: ${{ secrets.BUTLER_CREDENTIALS }}
              gameData: ./finalUnzipped
              itchUsername: ${{ env.ITCH_USERNAME }}
              itchGameId: ${{ env.ITCH_GAMEID }}
              buildChannel: macOS
              buildNumber: unwilting-${{ github.ref}}
    deploy_linux:
      needs: export_game
      runs-on: ubuntu-latest
      steps:
        - uses: actions/download-artifact@v2
          with:
            name: godot-export
            path: ./
        - name: Deploy - Itch.io - linux
          uses: KikimoraGames/itch-publish@v0.0.3
          with:
              butlerApiKey: ${{ secrets.BUTLER_CREDENTIALS }}
              gameData: ./Linux.zip
              itchUsername: ${{ env.ITCH_USERNAME }}
              itchGameId: ${{ env.ITCH_GAMEID }}
              buildChannel: linux
              buildNumber: unwilting-${{ github.ref}}
